# https://docs.netlify.com/build/configure-builds/file-based-configuration/

[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "https://mindoftay.com/*"
  to = "https://www.dontewhite.com/:splat"
  status = 301
  force = true
